version: '3.7'
services:
# uncomment the following lines to run an nginx proxy in front of api
#  nginx:
#    image: nginx:1.17
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8080:80
#    depends_on:
#      - api
  api:
    build:
      context: api
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
# possibly comment out following lines if running nginx proxy
    ports: 
      - 8888:8888 
    volumes:
      - ./api:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
